os: osx
language: swift
osx_image: xcode11.5
xcode_project: PokemonAPI.xcodeproj

matrix:
    include:
      - xcode_scheme: "PokemonAPI iOS"
        xcode_sdk: iphoneos13.5
        xcode_destination: "platform=iOS Simulator,OS=13.5,name=iPhone 11 Pro Max"
        script: xcodebuild clean test -project PokemonAPI.xcodeproj -scheme "PokemonAPI iOS" -destination "platform=iOS Simulator,OS=13.5,name=iPhone 11 Pro Max"

      - xcode_scheme: "PokemonAPI OSX"
        xcode_sdk: macosx10.15
        xcode_destination: platform=macOS
        script: xcodebuild clean test -project PokemonAPI.xcodeproj -scheme "PokemonAPI OSX" -destination "platform=macOS"

      - xcode_scheme: "PokemonAPI tvOS"
        xcode_sdk: appletvos13.4
        xcode_destination: "platform=tvOS Simulator,OS=13.4,name=Apple TV 4K"
        script: xcodebuild clean test -project PokemonAPI.xcodeproj -scheme "PokemonAPI tvOS" -destination "platform=tvOS Simulator,OS=13.4,name=Apple TV 4K"
        
      - xcode_scheme: "PokemonAPI watchOS"
        xcode_sdk: watchos6.2

cache: cocoapods
podfile: Example/Podfile
env:
  global:
    - FRAMEWORK_NAME=PokemonAPI
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install cocoapods
  - pod install --project-directory=Example
script:
  - pod lib lint --allow-warnings --quick
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: zNeWHJ+zUWOpc3hEeOAvoqmeknlM/wyjFizj6zAQ5Ow5Ep0yLIrtgUZHtENehFt6QxJQFttdX+4bK8pmJU8B9AovPk6iZcXoF9zAamyUHuMNdcIhkMyEVjuuekrQIcnDANGUhJGPHbGZ0vbIr+rf1YQ/t5Ob0YlHn/ckw8sJ14wRCjhFF6dgol/2AzvAFbxrYXBMtKZw2Vz9kI9wkTYDGy1vCnSFOdyRfWoYLaBgEfBV7p0ryHuKuXhhUz7Qxv8BxJvAB11QhCKCfXLC1YLCnkJEzy0k2b7x0j4xhZrgsi5BiCyRPbDICe0Ykjk/cNwRp/gIBqDEw0vofCm0wmAJ+94oudI2U+K8EzchawHF8aIACkEh1wxWzIczG+jgINm6TY1K8DEL4sfskw4KMYTazy7XnNHLtnBtwn/GNbiS+vP99NHTHR6a0RsPpizi+TcamntOfm0ayUHQH3cqQqr+DeAu18FkxclvIWrxNNf6zpFqcs73MZTbVitR6F9UAH8hnDJU/yCm1FO+am0bCfHnJL17Z9L36HshLa9bG4hzvw/+rU7Qvb1nkoR31CB0tc5SIeCvDS017KOm8XJTknZz7XnGPT15eOcVpxlfTlmooStt2gaDFxxNzO8qnDREwiEqgY5sIN3tAZolInFb9Y9XKjdoEd2HBmHFqAghVpGhSUs=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: kinkofer/PokemonAPI
    tags: true
